### ISSUE TITLE
Not able to start game

### ISSUE THREAD

**Issue by Tony-jdev** [EthosWallet/Sui8192#22]
0 0 0 0
0 2 0 0
2 0 0 0
0 0 0 0

I can't move them anywhere

**Comment by clionachee** [comment]
Hi @Tony-jdev,
It seems like you're having trouble moving the game pieces. Could you please provide more details about the issue? 

1. What steps did you take before encountering this issue?
2. Are there any error messages displayed on your screen? If yes, could you please share them?
3. What is the expected behavior and how does it differ from what you're experiencing?

If you have any of these additional details, feel free to put them up for the others to see the issue and provide an accurate solution.
